services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: aoka-api:latest
    restart: always
    network_mode: "host"      # !! контейнер использует сеть хоста
    environment:
      RAILS_ENV: production
      DATABASE_URL: <%= ENV["DATABASE_URL"] %>
      SECRET_KEY_BASE: <%= ENV["SECRET_KEY_BASE"] %>
      RAILS_LOG_TO_STDOUT: 'true'
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    command: bash -lc "bundle exec rails db:migrate && bundle exec rails s -b 0.0.0.0 -p 3001"
